rustler::atoms! {
    ok,
    error,
    done,
    closed,

    // Error kinds mapped from neo4rs::Error.
    invalid_config,
    io,
    neo4j,
    deserialization,
    unexpected_type,
    unexpected,
    argument,

    // Neo4jError fine-grained kinds.
    authentication,
    authorization_expired,
    token_expired,
    other_security,
    session_expired,
    fatal_discovery,
    transaction_terminated,
    protocol_violation,
    client_other,
    client_unknown,
    transient,
    database,
    unknown,

    // Tagged tuple for raw bytes payloads: {:bytes, binary}.
    bytes,

    // Map/struct key atoms.
    struct_key = "__struct__",
    calendar,
    year,
    month,
    day,
    hour,
    minute,
    second,
    microsecond,
    time_zone,
    zone_abbr,
    utc_offset,
    std_offset,
    id,
    labels,
    properties,
    start_node_id,
    end_node_id,
    nodes,
    relationships,
    indices,
    srid,
    x,
    y,
    z,
    months,
    days,
    seconds,
    nanoseconds,
    tz_id,
    offset_seconds,
    type_key = "type",
    time,
    naive,
    bookmark,
    available_after_ms,
    consumed_after_ms,
    query_type,
    stats,
    notifications,
    db,
    code,
    title,
    description,
    severity,
    category,
    position,
    offset,
    line,
    column,
    message,
    kind,
    // Counter fields.
    nodes_created,
    nodes_deleted,
    relationships_created,
    relationships_deleted,
    properties_set,
    labels_added,
    labels_removed,
    indexes_added,
    indexes_removed,
    constraints_added,
    constraints_removed,
    system_updates,

    // Elixir built-in struct module atoms.
    calendar_iso = "Elixir.Calendar.ISO",
    date_module = "Elixir.Date",
    time_module = "Elixir.Time",
    naive_datetime_module = "Elixir.NaiveDateTime",
    datetime_module = "Elixir.DateTime",

    // BoltexNif struct module atoms.
    node_module = "Elixir.BoltexNif.Node",
    relationship_module = "Elixir.BoltexNif.Relationship",
    unbound_relationship_module = "Elixir.BoltexNif.UnboundRelationship",
    path_module = "Elixir.BoltexNif.Path",
    point_module = "Elixir.BoltexNif.Point",
    duration_module = "Elixir.BoltexNif.Duration",
    bolt_time_module = "Elixir.BoltexNif.Time",
    bolt_datetime_module = "Elixir.BoltexNif.DateTime",
    datetime_zone_id_module = "Elixir.BoltexNif.DateTimeZoneId",
    summary_module = "Elixir.BoltexNif.Summary",
    counters_module = "Elixir.BoltexNif.Summary.Counters",
    notification_module = "Elixir.BoltexNif.Notification",
    input_position_module = "Elixir.BoltexNif.Notification.InputPosition",
    neo4j_error_module = "Elixir.BoltexNif.Neo4jError",
}
